[project]
name = "pines-rimas-analysis-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ['julian', 'astropy', 'numpy', 'matplotlib',
'pandas', 'pysftp', 'natsort', 'scipy',
'imageio', 'netCDF4', 'bs4', 'wget',
'photutils',
'progressbar', 'reportlab',
'astroquery', 'scikit-learn', 'batman', 'celerite', 'emcee', 'corner']
